default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ga82764.ap-south-1.aws
      user: "{{ env_var('dbt_user') }}"
      password: "{{ env_var('dbt_password') }}"
      role: ACCOUNTADMIN
      database: CHICAGO_DATA
      warehouse: compute_WH
      schema: levin
      threads: 5
      client_session_keep_alive: False